name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  checks:
    name: Main Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: ">=16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check formatting & linting
        run: npx @biomejs/biome check .

      - name: Run TS type checks
        run: yarn tsc

      - name: Build
        run: yarn build

  dead-code:
    name: Dead Code
    runs-on: ubuntu-latest
    needs: checks
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check for Dead Code
        run: npx ts-prune
